# Generated by Django 5.0.6 on 2024-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0008_alter_region_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomephoneTariff',
        ),
        migrations.DeleteModel(
            name='InternetTariff',
        ),
        migrations.DeleteModel(
            name='ModemTariff',
        ),
        migrations.DeleteModel(
            name='SmartTariff',
        ),
        migrations.DeleteModel(
            name='TVTariff',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bonustext',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
